### ISSUE TITLE
Нет redirect'a по ссылке

### ISSUE THREAD

**Issue by Xenely14** [EXBO-Studio/stalcraft-api#1]
Получил client_secret и client_id и делаю все согласно документации, но переадрессовки на мою ссылку не происходит, быть может я что-то делаю не так?

UPD: Поменял OAuth url (добавил порт), все также не помогает.

![изображение](https://user-images.githubusercontent.com/83385888/213924114-546fb899-ee68-4b08-841b-6d0b92513db7.png)
![изображение](https://user-images.githubusercontent.com/83385888/213924119-f0699293-1dee-4bed-8f96-9d10cc789138.png)

Переход и авторизация по ссылке "https://exbo.net/oauth/authorize?client_id=59&redirect_uri=http://127.0.0.1:5000/code&scope=&response_type=code" ничего не делает...

**Comment by abvadabra** [comment]
Значение `redirect_uri=http://127.0.0.1:5000/code` не совпадает с указанным при регистрации приложения редиректом, из-за чего сервер не завершает запрос на авторизацию. Настроенные редиректы можно поменять командой /myapps

**Comment by abvadabra** [comment]
Заметил проблему, действительно иногда могли не обновляться редиректы при изменение через бота. Сейчас должно быть исправлено, попробуйте изменить редирект и повторить авторизацию.

**Comment by Xenely14** [comment]
> Заметил проблему, действительно иногда могли не обновляться редиректы при изменение через бота. Сейчас должно быть исправлено, попробуйте изменить редирект и повторить авторизацию.

Попробовал, результат тот же даже после повторного изменения ссылки в боте

**Comment by abvadabra** [comment]
> > Заметил проблему, действительно иногда могли не обновляться редиректы при изменение через бота. Сейчас должно быть исправлено, попробуйте изменить редирект и повторить авторизацию.
> 
> Попробовал, результат тот же даже после повторного изменения ссылки в боте

И нашел еще одну проблему на эту же тему. Вот теперь то точно должно сработать :)

**Comment by Xenely14** [comment]
> > > Заметил проблему, действительно иногда могли не обновляться редиректы при изменение через бота. Сейчас должно быть исправлено, попробуйте изменить редирект и повторить авторизацию.
> > 
> > 
> > Попробовал, результат тот же даже после повторного изменения ссылки в боте
> 
> И нашел еще одну проблему на эту же тему. Вот теперь то точно должно сработать :)

Нет, все также ((

**Comment by abvadabra** [comment]
Судя по моим данным, теперь редирект обновился. Убедитесь, что редирект при запросе авторизации точно совпадает с редиректом в настройках приложения. Например, если при авторизации редирект указан как `http://127.0.0.1:5000/code`, то и в настройках приложения редирект должен быть указан как `http://127.0.0.1:5000/code`

**Comment by Xenely14** [comment]
> Судя по моим данным, теперь редирект обновился. Убедитесь, что редирект при запросе авторизации точно совпадает с редиректом в настройках приложения. Например, если при авторизации редирект указан как `http://127.0.0.1:5000/code`, то и в настройках приложения редирект должен быть указан как `http://127.0.0.1:5000/code`

Да, сработало, спасибо :)
