### ISSUE TITLE
API Demo - Emissions

### ISSUE THREAD

**Issue by michael-maia** [EXBO-Studio/stalcraft-api#11]
I was checking the API reference and saw that there is a endpoint for Emission Status, upon checking it on Postman i realized that every parameter is been updated every second.

This is suposed to happen? Or in the Production API time will be static based on what is happening in-game?

I wanted to test this just to see how the API works but don't know if I a misunderstood it.

Link used: https://dapi.stalcraft.net/NA/emission

**Comment by abvadabra** [comment]
Yes, demo api is designed to correctly respond to requests and realistically handle authentication, but the data it produces is meaningless. In case of emissions it will always just return current time offseted by some constant duration. Production API will return proper timings of emission start/end which only change when a new emission starts or currently active one ends.

**Comment by michael-maia** [comment]
Ok, thanks for the explanation.
