### ISSUE TITLE
Не могу сделать запрос к апи: не удалось выполнить запрос CORS

### ISSUE THREAD

**Issue by boraicho** [EXBO-Studio/stalcraft-api#12]
Подозреваю что проблема с авторизацией, уже по всякому пробовал играться с названием headers.
![изображение](https://user-images.githubusercontent.com/19574210/216408091-7432117f-0151-4fab-b1da-6e551e5fa1c0.png)

В ответ получаю это:
![изображение](https://user-images.githubusercontent.com/19574210/216410107-8641790b-015e-4c78-b272-0f2507ba79c1.png)

**Comment by abvadabra** [comment]
Дубликат #6 

Браузер ограничивает запросы к сторонним доменам, если в ответе на запрос не указано, что к нему действительно можно обратиться с текущей страницы. 

В вашей ситуации это значит, что запросы к апи следует делать с вашего собственного сервера, а не из браузера. В первую очередь потому, что иначе вы указываете секрет приложения прямо в клиенте, из-за чего его может взять кто угодно, и притвориться вашим приложением. Короче говоря, небезопасно так делать.
