### ISSUE TITLE
Проблема c "authorization code" и авторизацией по secret'у

### ISSUE THREAD

**Issue by Xenely14** [EXBO-Studio/stalcraft-api#2]
При попытке обратиться по ссылке: "https://exbo.net/oauth/token" получаю ошибку подобного типа:
`
{
   "error":"unsupported_grant_type",
   "error_description":"The authorization grant type is not supported by the authorization server.",
   "hint":"Check that all required parameters have been provided",
   "message":"The authorization grant type is not supported by the authorization server."
}
`

Все данные сверил, предполагаю, что проблема с client_secret

![изображение](https://user-images.githubusercontent.com/83385888/213931416-95b43a80-d2ea-4eea-8c69-828956161cdd.png)

**Comment by Xenely14** [comment]
Пытаюсь авторизоваться через secret, пишет, что я не авторизован:
![изображение](https://user-images.githubusercontent.com/83385888/213932837-866bff10-00ed-4ee5-8291-ea9682e6b1ef.png)

Запрос из примера срабатывает отлично:
![изображение](https://user-images.githubusercontent.com/83385888/213932890-93ae2dfb-4be6-4553-b80b-49f8efc170f2.png)
![изображение](https://user-images.githubusercontent.com/83385888/213932922-78af6737-0494-4d1f-bd24-3d0988b2b879.png)


P.S. Пытался менять secret. Безрезультатно...

**Comment by abvadabra** [comment]
> При попытке обратиться по ссылке: "https://exbo.net/oauth/token" получаю ошибку подобного типа: `{ "error":"unsupported_grant_type", "error_description":"The authorization grant type is not supported by the authorization server.", "hint":"Check that all required parameters have been provided", "message":"The authorization grant type is not supported by the authorization server." }`
> 
> Все данные сверил, предполагаю, что проблема с client_secret
> 
> ![изображение](https://user-images.githubusercontent.com/83385888/213931416-95b43a80-d2ea-4eea-8c69-828956161cdd.png)

Вероятнее всего, авторизация по коду не срабатывает из-за опечатки в название параметра `client_id` (вместо этого там `clint_id`)



> Пытаюсь авторизоваться через secret, пишет, что я не авторизован: ![изображение](https://user-images.githubusercontent.com/83385888/213932837-866bff10-00ed-4ee5-8291-ea9682e6b1ef.png)
> 
> Запрос из примера срабатывает отлично: ![изображение](https://user-images.githubusercontent.com/83385888/213932890-93ae2dfb-4be6-4553-b80b-49f8efc170f2.png) ![изображение](https://user-images.githubusercontent.com/83385888/213932922-78af6737-0494-4d1f-bd24-3d0988b2b879.png)
> 
> P.S. Пытался менять secret. Безрезультатно...

Тут проблема в том, что используется Demo API, которая не умеет авторизовывать реальные приложения. Оно принимает запросы только если используются данные, которые указаны в примере. Если заменить `dapi.stalcraft.net` на `eapi.stalcraft.net`, то должно сработать.

**Comment by Xenely14** [comment]
И впрямь сработало, спасибо :)
