### ISSUE TITLE
Активные лоты не работают

### ISSUE THREAD

**Issue by fifepls** [EXBO-Studio/stalcraft-api#27]
Информация которая приходит с метода активных лотов, присылает неактуальную информацию

**Comment by aidiors** [comment]
У меня такая же проблема. Уже третий день при проверке активных лотов присылается одна и та же информация, которая никак не соответствует лотам на аукционе.

**Comment by quantumsx** [comment]
@abvadabra 
Active Item Lots API поломалась.

**Comment by quantumsx** [comment]
FYI
Проблема все еще актуальна. Возвращаются как активные лоты, так и уже не существующие.
![image](https://github.com/EXBO-Studio/stalcraft-api/assets/140490094/8059afd4-426c-44d0-b839-58cb9ddb6caa)

**Comment by quantumsx** [comment]
@abvadabra Около 24 часов выглядело так, будто апи отрабатывает корректно. 
На данный момент опять появляются "фантомные" лоты, которые уже были выкуплены. При этом также перестают отображаться новые выставленные лоты.

**Comment by quantumsx** [comment]
@fifepls А зач ты тему закрыл?

**Comment by aidiors** [comment]
Я открыл заново
