### ISSUE TITLE
API Limits and refresh rate.

### ISSUE THREAD

**Issue by Kamer5555** [EXBO-Studio/stalcraft-api#3]
Hello, so my question are: 
Are there any limitations on API right now? 
How many requests can we make in one minute? 
How fast is API refreshing?, I'm talking about emission timer and shop mostly.

Thanks for any answers.

**Comment by abvadabra** [comment]
API service utilizes [token bucket algorithm](https://en.wikipedia.org/wiki/Token_bucket) for rate limiting implementation. Every minute an application gets 100 tokens allocated for it and any API requests will consume some amount of tokens from that bucket. Once there are no more tokens to consume all requests will fail with 429, until the bucket has been refilled. 

Different endpoints have different costs, e.g. emission endpoint has cost of 1, and auction requests have cost of 2. 

However, costs and allocated amount of tokens have been choosen somewhat arbitrary with a goal to evaluate backend service performance and change it to something more meaningful in the future. That is primarily the reason why there is no page about rate limits in the docs.

**Comment by abvadabra** [comment]
Regarding data refresh rate, emission data is update every 10-15 seconds, and auction data is provided in real-time from the same database which the game is using.

**Comment by Kamer5555** [comment]
Awesome, thanks. This is really good that market is in real-time.

**Comment by loreadmack** [comment]
> Regarding data refresh rate, emission data is update every 10-15 seconds, and auction data is provided in real-time from the same database which the game is using.

Hello, please can u explain me how did u done real-time interaction?
