### ISSUE TITLE
API emissions

### ISSUE THREAD

**Issue by antondevya9** [EXBO-Studio/stalcraft-api#37]
I don't understand why the api outputs incorrect data. For example, it is now 10:38 (Moscow). The emission was at 8:40 (Moscow). 

The API outputs:
```
current_start=None
previous_start=datetime.datetime(2024, 7, 19, 5, 38, 53, tzinfo=datetime.timezone.utc)
previous_end=datetime.datetime(2024, 7, 19, 5, 42, 53, tzinfo=datetime.timezone.utc)
```

API says that the emission was 5:38. But if you look at the official STALCRAFT bot in VK, which correctly notifies about emissions, then the emission was 8:40. 

I'm NOT using a DEMO API. I have access to the official api.

RU server.

**Comment by antondevya9** [comment]
Кто шарит, помогите а.....

**Comment by midnighter32** [comment]
Апи возвращает время  для UTC-0
![image](https://github.com/user-attachments/assets/a4c72e45-8534-49ca-9c86-ed5cc800df7b)
Московское время UTC+3. Прибавь ко времени начала и конца 3 часа, и всё совпадёт
![image](https://github.com/user-attachments/assets/482fc369-a2e4-4840-802c-06763f2f1007)
