### ISSUE TITLE
НЕ РАБОТАЕТ АПИ                           НЕТ ДОСТУПА К АПИ

### ISSUE THREAD

**Issue by 10ffe0006822** [EXBO-Studio/stalcraft-api#46]
По совету одно человека ниже получил токен я через консоль официального сайта exbo.net 
{
  "title": "Rate limit exceeded",
  "status": 429,
  "details": {}
}
выдаёт во такую ошибку 
мой ник в тг Рябчик
(Рябчик это имя кошака у меня на аватарке)

**Comment by 10ffe0006822** [comment]
@abvadabra

**Comment by midnighter32** [comment]
На пользовательские токены не выдаётся лимит на запросы к API. Это можно увидеть по данным Header'ам 
![image](https://github.com/user-attachments/assets/dd910d39-788f-4e12-9ac3-392119ec9b28)
Вам нужен либо пользовательский токен полученный через зарегестированное приложение. У него лимит 50 поинтов (25 запросов)
![image](https://github.com/user-attachments/assets/21edc248-82f7-4095-868d-f2f07fc4b5ce)
Либо токен самого приложения. У него 400 поинтов (200 запросов)
![image](https://github.com/user-attachments/assets/49a0a45e-e2e5-43e5-ac80-270d3c21c017)

x-ratelimit-limit - Максимальное количество поинтов
x-ratelimit-remaining - Оставшееся количество поинтов до обновления
x-ratelimit-reset - Время, когда лимит данного токена обновится (В формате UNIX Timestamp)

**Comment by midnighter32** [comment]
Для проверки вашего токена можете отправить запрос через Curl
Вот пример:
```bash
curl --request GET --url https://eapi.stalcraft.net/ru/auction/y1q9/lots --header 'Authorization: Bearer ТутВашТокен' --header 'Content-Type: application/json' -I
```

**Comment by 10ffe0006822** [comment]
@Midnighter32 это ясно
не ясно одно как долго ждать достук к апи я уже 3 месяца жду

**Comment by midnighter32** [comment]
Ну я ждал месяц. Мой знакомый ждал пару дней. Тут как повезёт.

**Comment by 10ffe0006822** [comment]
@Midnighter32 
видимо я самый не везучий

**Comment by MOBLOL** [comment]
> [@midnighter32](https://github.com/midnighter32) видимо я самый не везучий

Я отправил запрос 3 марта, получил 1 марта ... (без шуток)
