### ISSUE TITLE
проблема с токеном

### ISSUE THREAD

**Issue by 10ffe0006822** [EXBO-Studio/stalcraft-api#47]
401 Unauthorized
{
  "title": "Unauthorized",
  "status": 401,
  "details": {
    "token": "Corrupted or illegal authorization token"
  }
}
получил доступ к апи на сайте (https://eapi.stalcraft.net/reference#/paths/region--emission/get) ввожу  токен c Bearer и выдаёт ошибку

**Comment by midnighter32** [comment]
Проверь свой токен на данном сайте https://jwt.io. Является ли он валидным JWT токеном?

**Comment by 10ffe0006822** [comment]
![Снимок экрана 2024-12-01 144620](https://github.com/user-attachments/assets/454618bb-4f70-455f-b74e-a19a81e1a5bd)

**Comment by 10ffe0006822** [comment]
я плохо читал документацию

**Comment by qReolq** [comment]
Как исправил?
