### ISSUE TITLE
Database half empty.

### ISSUE THREAD

**Issue by Kamer5555** [EXBO-Studio/stalcraft-api#5]
Hey, can you add materials and other items to your current database which is on github? Thanks.

**Comment by abvadabra** [comment]
For initial release the decision has been made to provide only information about items which are shown on the guide page in the in-game PDA. We may reevalute that policy in the future, however I can not promise anything for now.

**Comment by midnighter32** [comment]
Hello. 
Is it still impossible to obtain information or at least identifiers of some unlisted items?
