### ISSUE TITLE
Auction Lots

### ISSUE THREAD

**Issue by seregkaj** [EXBO-Studio/stalcraft-api#7]

**Comment by seregkaj** [comment]
![image](https://user-images.githubusercontent.com/79603162/213943593-781c2335-31ce-4e1a-9ce7-4b04a4bda052.png)
Добрый вечер!
Пытаюсь передать в параметр offset значение отступа от начала, но запрос всегда возвращает один и тот же список.

**Comment by abvadabra** [comment]
Возможно будет проще разобраться, если покажете пример запроса или код, который его выполняет.

**Comment by EtoZheJih** [comment]
Может ты пытаешься передать их в теле жсоном?
Просто на примере такой фабрики (если максимально упростить) всё отрабатывает штатно.
![изображение](https://user-images.githubusercontent.com/81481817/213965471-4722bedc-a7a1-42e2-8dc4-87a21d1d985b.png)
